server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: department-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/department_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  boot:
    admin:
      client:
        instance:
          management-base-url: http://localhost:8081
application:
  config:
    department-url: http://localhost:8081/api/v1/department